### ISSUE TITLE
Animation Issue With ColumnSeries When Scroll Screen After setState

### ISSUE THREAD

**Issue by sujalBandhara** [syncfusion/flutter-examples#68] opened 2020-01-07 08:55 UTC
Hello,

I am facing reanimate animation issue when scrolling  screen after setState in ColumnSeries chart. Is there any way to restrict the animation when user scroll the screen.

Note :: dataSource change dynamically on change of button selections.

**Comment by dharanidharandharmasivam** [comment] 2020-01-08 13:38
Hi @sujalBandhara ,

Greetings from Syncfusion. We have analyzed your query and we couldn’t predict your exact scenario. So, kindly share with us your sample or the screenshot which replicates your scenario. This will be much helpful in further analysis and provide you the solution sooner. 

Thanks,
Dharani.

**Comment by sujalBandhara** [comment] 2020-01-09 05:31
Widget allUsageBarChart() 
{
 final syncfusionUsageBarChart = SfCartesianChart( 
primaryXAxis: CategoryAxis( majorGridLines: MajorGridLines( width: 0, color: colorThemeGreyDashedLine, dashArray: [8, 8]), isVisible: true, ), // Enable legend legend: Legend(isVisible: false), 
// Enable tooltip tooltipBehavior: TooltipBehavior( textStyle: ChartTextStyle( color: colorThemeWhite, fontSize: 12, fontWeight: FontWeight.bold), shadowColor: Colors.transparent, enable: true, color: colorThemeBlack, canShowMarker: false, format: ' point.y\t' + getUnitForTooltip(), shouldAlwaysShow: true, header: ""), 
series: [ ColumnSeries<UsageAllData, String>( dataSource: _getChartCurrentData(), xValueMapper: (UsageAllData data, _) => data.year, yValueMapper: (UsageAllData data, _) => data.data, // Map color for each data points from the data source pointColorMapper: (UsageAllData data, _) => Helper.getColorForUsageBarChart(data.data,selectedButton)) ]);
 return Container(child: syncfusionUsageBarChart); 
}

List _getChartCurrentData() {
 if (selectedButton == 1) { return usageData1; } if (selectedButton == 2) { return usageData2; } if (selectedButton == 3) { return usageData3; } else { return usageData4; }
 }


 @override
  Widget build(BuildContext context) {
return new Scaffold(
body:ListView(
                                  children: <Widget>[
allUsageBarChart()
])

)
}

> For above code when i changed the selectedButton and after it when scrolled the screen then graph reanimate. It's only generate after changed of selectedButton value using setState normally working fine.

**Comment by dharanidharandharmasivam** [comment] 2020-01-09 18:22
Hi @sujalBandhara ,

Thanks for the revert. We would like to let you know when a widget is rendered in the **ListView** widget, then if a widget moves out of the viewport and again comes into the viewport on scrolling, the widget will be reinitialized. This is the default behavior of ListView, so the chart gets animated on scrolling. If you wish not to animate, then you can render the chart using the **SingleChildScrollView** widget, using this on scrolling the widget will not get reinitialized. 

We have prepared a sample based on the above scenario and the sample can be found from the below link.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1845822077 

Thanks,
Dharani.

**Comment by EzekR** [comment] 2020-01-16 07:57
I got the same problem, and my solution is using a flutter plugin [should_rebuild](https://github.com/fantasy525/should_rebuild). With this plugin, chart only rebuilds when the data passed to it changes. Hope this will help you.

**Comment by saravanakumar007** [comment] 2020-01-22 12:17
Hi @sujalBandhara  ,

Thanks for revert. We would like to let you know that when any widget rendered in the ListView, it will do the rebuild with reinitializing (InitState called every rebuild) its widgets when we scrolling. That’s why Chart widget also re-rendered with animate in order to overcome this issue we have prepared some workaround sample for you. In this sample, we have prevented the chart animate when scrolling.

We have prepared a sample based on the above scenario and the sample can be found from the below link.

Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1845822077-1186357010.zip

Note: We have prepared the sample just for your requirements. So based on your scenario,  you can change the sample.

Regards,
Saravana Kumar K

**Comment by jkoenig134** [comment] 2020-01-30 07:54
Hi, I am using a StaggeredGridView and the workarounds doesn´t work for me. Is there any other Idea?

**Comment by DeviArunaMurugan** [comment] 2020-01-31 08:39
Hi @jkoenig134 ,

We have tried to reproduce the reported issue using the SfRadialGauge inside the StaggeredGridView widget. Unfortunately, we are unable to reproduce the issue. Could you kindly modify the below sample in order to reproduce the reported issue?

Output:
![image](https://user-images.githubusercontent.com/55730024/73524469-30256780-4433-11ea-92c2-35719cbf6fb5.png)

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/gauge_gridview1009360131.zip

Regards,
Devi

**Comment by jkoenig134** [comment] 2020-01-31 08:48
Hi @DeviArunaMurugan, thanks for your reply!
My gauges are all updated by streams and there are much more gauges than in the provided image and they are completely of the screen.
Hope it helps, otherwise i will reproduce that in your example.

**Comment by jkoenig134** [comment] 2020-01-31 09:21
@DeviArunaMurugan I tried to reproduce it in the last 30 minutes, didn´t get it. Then i switched back to my application to see the difference. And the error is gone. Seems like the app fixed itself.

**Comment by dharanidharandharmasivam** [comment] 2020-02-04 06:23
Hi @jkoenig134 ,

Thanks for the revert. We confirm your issue has been resolved and thus we are closing this issue.

Thanks
Dharani.

**Closed** 2020-02-04 06:23 UTC
