### ISSUE TITLE
[SfDataGrid] [BugFix] When only one row, ColumWidth fitByValue failed

### ISSUE THREAD

**Issue by YancyHsu** [syncfusion/flutter-examples#860] opened 2024-07-07 18:06 UTC
two or more it works well, so maybe somewhere rowindex start from 1? i cant find it in the source code

**Comment by YancyHsu** [comment] 2024-07-08 01:15
[https://github.com/syncfusion/flutter-widgets/blob/ee87b7b6a735a9a303d7e7973fa4540d0337b64e/packages/syncfusion_flutter_datagrid/lib/src/datagrid_widget/runtime/column.dart#L656](url)

```
if (startRowIndex <= 0 && endRowIndex <= 0) {
      return column._actualWidth;
    }
```

just annotation it, or revise to:

```
if (startRowIndex < 0 && endRowIndex < 0) {
      return column._actualWidth;
    }
```
then it is ok to run only one row datasource

**Comment by abineshPalanisamy** [comment] 2024-08-05 12:23
Hi @YancyHsu ,

We have checked your query at our end, and we are able to replicate that issue at our end. We have considered this as a  bug and logged a bug report regarding this in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release, which is expected to be rolled out on August 20, 2024. We will let you know once released, and we appreciate your patience until then. 

 Disclaimer: Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization. 


Regards,
Abinesh P

**Comment by abineshPalanisamy** [comment] 2024-08-20 11:50
Hi @YancyHsu ,

We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([26.2.10](https://pub.dev/packages/syncfusion_flutter_datagrid)). 

**Root cause :** We previously implemented a condition to calculate the cell width when the effective rows are empty. This condition is the root cause of the bug. The issue occurs because the condition checks if endIndex <= 0. However, the endIndex is 0 whether the effective rows are empty or contain a single row.

If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment] 2024-09-02 04:29
Hi @YancyHsu,

We believe that the reported issue has been resolved in the latest DataGrid version. Hence, we are closing this issue. If you need any further assistance, please reopen this ticket. We are always happy to help you.

Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-09-02 04:29 UTC
Labels: bug, data grid, waiting for customer, fixed
