### ISSUE TITLE
In  Flutter 1.15.3-pre.37 : Upon Importing SyncFusion Charts Flutter build process throws error in _painter._calculateLocation(const Offset(null, null));

### ISSUE THREAD

**Issue by cygnus-glx** [syncfusion/flutter-examples#80] opened 2020-02-11 04:48 UTC
Flutter Version Info:

Flutter 1.15.3-pre.37 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6dc3bfaa98 (3 days ago) • 2020-02-07 18:28:02 -0800
Engine • revision 6158f03ef5
Tools • Dart 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

Error Message : 

Compiler message:
/C:/Users/Sagar/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-17.4.46/lib/src/common/user_interaction/tooltip.dart:345:52: Error: Constant evaluation error:
  void hide() => _painter._calculateLocation(const Offset(null, null));
                                                   ^
org-dartlang-sdk:///flutter/lib/ui/geometry.dart:15:9: Context: This assertion failed.
  const OffsetBase(double dx, double dy)
        ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 817

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value

**Comment by cygnus-glx** [comment] 2020-02-11 04:51
Code Used while caught this error 👍 

// import 'package:flutter/material.dart';
// import 'package:peak/models/radialChartModel.dart';
// import 'package:syncfusion_flutter_charts/charts.dart';

// class RadialBarChartWidget extends StatefulWidget {
//   RadialBarChartWidget({Key key}) : super(key: key);

//   @override
//   _RadialBarChartWidgetState createState() => _RadialBarChartWidgetState();
// }

// class _RadialBarChartWidgetState extends State<RadialBarChartWidget> {


//   final List<RadialBarChartModel> chartData = <RadialBarChartModel>[
//     RadialBarChartModel(
//         x: 'John',
//         y: 10,
//         text: '100%',
//         pointColor: const Color.fromRGBO(248, 177, 149, 1.0)),
//     RadialBarChartModel(
//         x: 'Almaida',
//         y: 11,
//         text: '100%',
//         pointColor: const Color.fromRGBO(246, 114, 128, 1.0)),
//     RadialBarChartModel(
//         x: 'Doe',
//         y: 12,
//         text: '100%',
//         pointColor: const Color.fromRGBO(61, 205, 171, 1.0)),
//     RadialBarChartModel(
//         x: 'Tom',
//         y: 13,
//         text: '100%',
//         pointColor: const Color.fromRGBO(1, 174, 190, 1.0)),
//   ];

//   @override
//   Widget build(BuildContext context) {
//     return Container(
//        child: SfCircularChart(
//                         series: <CircularSeries>[
//                             RadialBarSeries<RadialBarChartModel, String>(
//                                 dataSource: chartData,
//                                 xValueMapper: (RadialBarChartModel data, _) => data.x,
//                                 yValueMapper: (RadialBarChartModel data, _) => data.y,
//                                 // Corner style of radial bar segment
//                                 cornerStyle: CornerStyle.bothCurve
//                             )
//                         ]
//                     )
//     );
//   }
// }

**Comment by Dharanipalani** [comment] 2020-02-11 13:49
Hi Cygnus,
 
Thanks for using our Flutter Widgets.
 
We have analyzed your scenario and the issue is because of building our widgets on the master channel. Our Flutter widgets are compatible with the stable channel. You can try our widgets by downgrading or upgrading the versions in the stable channel that will work fine. And if you are using the master channel for any specific reasons, kindly revert us with the reason for using master. This will be much helpful in providing the solution sooner.

Regards,
Dharanitharan

**Comment by agilob** [comment] 2020-02-16 19:51
That means in one of the soon future releases of Flutter your library will stop working, so maybe better to address it sooner than later?

**Comment by JayavigneshwaranG** [comment] 2020-02-17 07:27
Hi @agilob ,

Yes we understand. While updating our packages in pub, we will check its compatibility with the latest Flutter versions and resolve all the issues. So it can used without any hurdles. Also we will resolve these issues in our next pub update. We will let you know once it is published. 

We appreciate your patience until then.

Thanks,
Jayavigneshwaran

**Comment by joaowd** [comment] 2020-02-17 10:18
Same problem:

>     Compiler message:
>     /development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-17.4.46/lib/src/common/user_interaction/tooltip.dart:345:52: Error: Constant evaluation error:
>       void hide() => _painter._calculateLocation(const Offset(null, null));
>                                                        ^
>     org-dartlang-sdk:///flutter/lib/ui/geometry.dart:15:9: Context: This assertion failed.
>       const OffsetBase(double dx, double dy)

**Comment by tbm98** [comment] 2020-02-23 06:10
same problem with dev channel

**Comment by cygnus-glx** [comment] 2020-03-05 04:05
I recon this issue on master channel. And have switched to stable channel
with no issues.

Thanks for reply.

Regards,
Sagar

**Comment by jkoenig134** [comment] 2020-03-18 17:06
I also have that issue. I need the master channel, because i build my apps also on windows. Can you deploy a version in that this is fixed for the master channel?

**Comment by jkoenig134** [comment] 2020-03-18 17:19
@JayavigneshwaranG i tried it out. It´s just removing the const keyword and it works perfectly.

**Comment by dharanidharandharmasivam** [comment] 2020-03-24 12:17
Hi All,

Thanks for being patience. The reported issue has been fixed in our vol 1 beta release 2020, however with the master channel, while initializing our widgets, you will get an error (The type 'Diagnosticable' can't be used as supertype). The reason behind this is, in a stable/beta channel, the type of Diagnosticable will be an abstract class and in the master channel, it will be of mixin type. So, we recommend using the stable channel in which all our widgets will work properly.

Thanks,
Dharani.

**Closed** 2020-03-30 04:34 UTC

**Comment by joaowd** [comment] 2020-04-09 18:36
Does it work in dev channel ?

**Comment by Tejaswgupta** [comment] 2020-08-30 06:25
This issue still exists on master channel.

**Comment by SriramKiranSenthilkumar** [comment] 2020-08-31 06:18
Hi @Tejaswgupta ,

We have analyzed your scenario and we tried to replicate the reported issue with the latest master channel of flutter and also with our latest flutter widget version (**18.2.55**). Unfortunately, the application was building and running fine and the reported issue didn't occur at our end. So, we kindly request you to upgrade your Flutter master channel SDK version and also our Flutter widget version to the latest version to overcome the reported issue. 

Also, if the problem persists even after upgrading to the latest versions, kindly revert us with more information on the Flutter SDK version along with our Flutter widget version which you are using in your project so that it will help provide the solutions sooner.

Regards,
Sriram Kiran
