### ISSUE TITLE
Low speed Chart

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#278] opened 2021-02-06 12:11 UTC
Your chart performs extremely poorly on 500 candlesticks
please see this video 
[](https://vimeo.com/user108517719/review/509174535/faff05e7f8)

https://vimeo.com/user108517719/review/509174535/faff05e7f8

My phone is Samsung S10 plus

**Comment by m2faridi** [comment] 2021-02-06 12:15
this code for sync all chart

```
double zoomPosation=0;
  double zoomFactor=0.15;
  void chartZoomSync(ZoomPanArgs zoomingArgs ,int index){
    if (zoomingArgs.axis.name != null && int.parse(zoomingArgs.axis.name) == index) {
      if(zoomingArgs.currentZoomPosition!=zoomPosation || zoomingArgs.currentZoomPosition!=zoomingArgs.currentZoomFactor)
      {
        zoomPosation = zoomingArgs.currentZoomPosition;
        zoomFactor = zoomingArgs.currentZoomFactor;
        setState(() {

        });
      }
    }
  }
```

`      onZooming: (zoomingArgs) {
        chartZoomSync(zoomingArgs,index);
      }`

**Comment by m2faridi** [comment] 2021-02-06 12:19
I would love to use your library in the program I am working on, but unfortunately the speed of your library is not good at the moment.
I am currently using the mpFlutterChart Library
Please fix speed issues. Thank you
link app

https://play.google.com/store/apps/details?id=com.m3.Trendo
[](https://play.google.com/store/apps/details?id=com.m3.Trendo)

**Comment by Dharanipalani** [comment] 2021-02-09 12:59
Hi @m2faridi, 
 
Thanks for the interest in our Flutter charts. We have analyzed your scenario and the problem is due to calling the **setState** in **onZooming** event in the sample level. We have handled this in the source level, the **onZooming** event will fires automatically while zooming and the assigned **zoomFactor** and **zoomPosition** values will be updated, so no need to call the **setState** to update them. We have attached the sample and screen record for your reference please make use of it. 

Sample:  [https://www.syncfusion.com/downloads/support/directtrac/314111/ze/I314111-candle_performance1745787120 ](url)

screenshot for updating zoomFactor and zoomPosition values,

![image](https://user-images.githubusercontent.com/19763272/107366869-a2c82900-6b04-11eb-8a89-9ffa407b3b28.png)

Screen record: [https://www.syncfusion.com/downloads/support/directtrac/314111/ze/I314111-candle_record-1063564876 ](URL)

Please revert us if you need any further assistance. 

Thanks, 
Dharanitharan. P

**Comment by m2faridi** [comment] 2021-02-09 13:24
Screen record: https://www.syncfusion.com/downloads/support/directtrac/314111/ze/I314111-candle_record-1063564876

I do not have access to this page
Access Denied
You don’t have permission to access this file. The reason may be:
The incident associated with this file is not tied to the account you used to log in. To Logout use this link.
Your enterprise portal admin has not allowed you to access other portal users’ incidents. Ask admin to change the support visibility in their Syncfusion profile.
If you feel this information is wrong and you need to download this file, please contact us.

**Comment by m2faridi** [comment] 2021-02-09 13:31
Performance is still very poor

**Comment by Dharanipalani** [comment] 2021-02-10 06:41
Hi @m2faridi,

We regret the inconvenience that caused. Now, we attached the sample and screen record below please make use of it and revert us if you have further concerns.

Sample: [I314111-candle_performance.zip](https://github.com/syncfusion/flutter-examples/files/5956303/I314111-candle_performance.zip)

Screen-record: [I314111-candle_record.zip](https://github.com/syncfusion/flutter-examples/files/5956305/I314111-candle_record.zip)

Thanks,
Dharanitharan. P

**Comment by m2faridi** [comment] 2021-02-10 12:13
I replaced your codes
But it was not high speed
For example, run the same code with 5000 candlesticks and it will slow down

**Comment by m2faridi** [comment] 2021-02-10 12:19
Please check the speed of this chart
https://github.com/SunPointed/MPFlutterChart

**Comment by Dharanipalani** [comment] 2021-02-11 13:47
Hi @m2faridi,

When we use more points, the performance lag occurs while zooming. However, we are trying to improve the performance for the candle type series which will be included for vol 1 main release which is expected to be rolled out at the end of March 2021. We appreciate your patience till then. We appreciate your patience until then.

Regards,
Dharanitharan. P

**Comment by Dharanipalani** [comment] 2021-04-01 09:02
Hi @m2faridi,

Thanks for being patience. We are glad to inform you that the reported performance issue in the candle series is fixed and here we shared the performance metrics for your reference. We are continuously working on performance improvement and it will be in our upcoming releases.

**Performance metrics:**

Before Improvement | After improvement
-- | --
Candle | Candle
1.5k - initial zoom - 3000 ms (3s)                   further zoom - 1500ms (1.5s) | 1.5k - initial zoom - 800ms (0.8s)                    further zoom - 100ms (0.1s)
5k - initial zoom - 15000 ms(15s)          - further zoom - 10000 ms (10s) | 5k - initial zoom - 8000 ms (8s)           further zoom - 2000 ms (2s)
  |  
Spline | Spline
1.5k - initial zoom - 130ms                   further zoom - 70ms | 1.5k - initial zoom - 70ms                     further zoom - 20ms
5k   - initial zoom - 400ms                further zoom - 200ms | 5k - initial zoom -   210ms              further zoom -  60ms

To resolve the performance issue, you can upgrade our charts from the below link.
[https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.54+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.54+1)

Thanks,
Dharanitharan. P

**Closed** 2021-04-08 05:36 UTC

**Comment by m2faridi** [comment] 2021-04-08 11:31
Improved, but we still have lag. Optimize when zooming and moving
