### ISSUE TITLE
addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by s2yed** [syncfusion/flutter-examples#656] opened 2022-07-27 08:24 UTC
ub.dartlang.org/syncfusion_flutter_datepicker-20.2.40/lib/src/date_picker/date_picker.dart:9826:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.

**Comment by Indumathi1195R** [comment] 2022-07-28 05:41
Hi,

Based on the shared information, we have checked the mentioned issue “**Error occurred while using the SchedulerBinding  method in the Flutter Event  DateRangePicker**” in simple sample and we are unable to reproduce the any error from our end. Also please find the tested details from the below.

**Flutter Version:** Channel stable – 3.0.0
**Flutter DateRangePicker version:** 20.2.40

Can you please confirm are you using the latest Flutter version, if not kindly use the latest version and let us know still if you are facing same issue? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by BenSalemOumaima** [comment] 2022-08-15 11:16
Hello @Indumathi1195R ,

I am facing the same issue with flutter 2.10

**Comment by Indumathi1195R** [comment] 2022-08-26 05:51
Hi,

Kindly update the Flutter to 3.0.0 version and syncfusion_flutter_datepicker to 20.1.56 for resolving this issue. Please get in touch with us if would you require any further assistance.

Regards,
Indumathi R

**Closed** 2022-12-28 10:40 UTC
