### ISSUE TITLE
Exception when hiding a series

### ISSUE THREAD

**Issue by MsXam** [syncfusion/flutter-examples#9] opened 2019-08-14 11:43 UTC
When you tap on a legend to hide a series, then tap the graph - you get an exception :

The following NoSuchMethodError was thrown while dispatching a pointer event:
The method 'contains' was called on null.
Receiver: null
Tried calling: contains(Instance of 'Offset')
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
#1      _ContainerArea._bindInteractionWidgets._findSeries 
package:syncfusion_flutter_charts/…/base/chart_base.dart:1438
#2      _ContainerArea._bindInteractionWidgets.<anonymous closure> 
package:syncfusion_flutter_charts/…/base/chart_base.dart:1532
#3      RenderPointerListener.handleEvent 
package:flutter/…/rendering/proxy_box.dart:2683
#4      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
...
Event: PointerDownEvent#4e7ef(position: Offset(238.7, 473.0), timeStamp: 89:38:41.622606, pointer: 96, kind: touch, device: 140607296318576, buttons: 1, down: true, pressure: 0.0, pressureMin: 0.0, pressureMax: 6.7, radiusMajor: 6.7, radiusMin: 5.0, radiusMax: 8.3, orientation: -1.6)
    position: Offset(238.7, 473.0)
Target: RenderPointerListener#992e2 relayoutBoundary=up1
    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=307.0, 0.0<=h<=450.0)
    size: Size(307.0, 450.0)
    behavior: deferToChild
    listeners: down, move, up

**Comment by JayavigneshwaranG** [comment] 2019-08-15 12:58
Hi MsXam,

We have analyzed this and tried to replicate the reported issue at our end. But unfortunately, we couldn’t replicate this. Series visibility is toggled properly while clicking the legend, without any exception. We have attached the sample which we used for testing in the below link for your reference. Here we have specified 3 series (line, spline and column).
https://www.syncfusion.com/downloads/support/directtrac/245156/ze/CHART_~1-110926928

Attached the screen recorded video in the below link for your reference.
https://www.syncfusion.com/downloads/support/directtrac/245156/ze/201908~1-482761390

As we didn’t know your exact scenario, we couldn’t replicate this. We request you to revert your sample code or revert the sample which we have attached, by modifying your scenario in it. This will be helpful for us to reproduce the issue and to resolve it ASAP.

Also please ensure whether you were using the latest version(1.0.0-beta.3) of our package in your example and use latest Flutter SDK.

Thanks,
Jayavigneshwaran

**Comment by MsXam** [comment] 2019-08-15 13:11
The exception doesnt cause the app to fail unless you enable a breakpoint in VSCODE set to ALL EXCEPTIONS or UNCAUGHT EXCEPTIONS - you will then see the exception stack trace in your console.

**Comment by dharanidharandharmasivam** [comment] 2019-08-19 16:24
Hi @MsXam ,

Sorry for the inconvenience. Yes, we can replicate the issue on toggle the column series visibility and the issue is not replicated with spline type series. So, we have logged a bug report in our feedback portal. You can track the status of the bug from the below link.

[Feedback Link](https://www.syncfusion.com/feedback/8284) 

We will fix the bug and include it in our upcoming release. We appreciate your patience until then. Please let us know if you have any concerns.

Thanks,
Dharanidharan.

**Comment by dharanidharandharmasivam** [comment] 2019-08-29 16:52
Hi @MsXam ,

Thanks for being patience. We have fixed the reported issue. The exception will not be thrown on hiding the series. To resolve the issue, kindly upgrade your package and you can find the updated packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts 

Kindly revert us if you have any concerns.

Thanks,
Dharani.

**Comment by JayavigneshwaranG** [comment] 2019-08-30 09:47
Hi @MsXam  ,

We are closing this issue now, as it is resolved.
If you still face any concerns, please create a support incident(https://www.syncfusion.com/support/directtrac/incidents/newincident) for better follow up, we will update the responses there.

Thanks,
Jayavigneshwaran

**Closed by JayavigneshwaranG** 2019-08-30 09:47 UTC
