### ISSUE TITLE
If you sign faster, the sign will get worse.

### ISSUE THREAD

**Issue by murodjon-sattorov** [syncfusion/flutter-examples#786] opened 2023-05-31 12:07 UTC
When the signature is drawn faster, its lines merge with other lines.![IMAGE 2023-05-31 17:04:50](https://github.com/syncfusion/flutter-examples/assets/68753701/15622493-3e58-4422-8b51-1aae67a6654d)

**Comment by muhiddinxon** [comment] 2023-06-12 06:27
this issue is being observed in version 3.10.0 of flutter, if i downgrade to 3.7.0 version of flutter , it is working fine , please fix this issue

**Comment by gabrielbertollo** [comment] 2023-08-07 13:58
This also seems to be an iOS problem, in Android, I could not reproduce it. Also, after upgrading to Flutter 3.10.0, the SignaturePad widget's performance got very bad in iOS, even causing crashes sometimes.

**Comment by karniv00l** [comment] 2023-08-08 06:28
I think that Impeller on iOS is now enabled by default

**Comment by LavanyaGowtham2021** [comment] 2024-02-14 09:43
Hi @murodjon-sattorov 

We have checked the reported issue with [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) and have reproduced it at our end. This issue is replicated with 3.10.0 and later Flutter SDK versions because Flutter uses an impeller rendering engine for iOS by default. Disabling the impeller by following the steps mentioned in the below link can resolve your issue.


Link: https://docs.flutter.dev/perf/impeller#ios

**Comment by VijayakumarMariappan** [comment] 2024-07-05 03:39
Hi @murodjon-sattorov @muhiddinxon @gabrielbertollo @karniv00l 

We would like to inform you that the reported issue of facing performance and rendering issues while drawing a signature in the SignaturePad widget, which was replicated in versions 3.10.0 and later, has been resolved in the latest Flutter SDK version 3.22 from the Flutter framework. Kindly upgrade your Flutter SDK to version 3.22.

**Closed** 2024-09-05 04:06 UTC
Labels: signature pad, waiting for customer
