### ISSUE TITLE
pie chart displaying with out circle  but still showing  legend and labels are displaying

### ISSUE THREAD

**Issue by gopibathini** [syncfusion/flutter-examples#669] opened 2022-08-31 11:22 UTC
![pie_chart_null_issue](https://user-images.githubusercontent.com/89006280/187666909-bbe2b86a-f4d8-4ef9-9d57-459578b6adaf.PNG)

iam getting  issue as null check operator used on a null value.

This issue occurs once or twice when opens the app

**Comment by SriramKiranSenthilkumar** [comment] 2022-09-01 14:25
Hi @gopibathini,

Greetings from Syncfusion.

We have checked your query at our end, and we tried to replicate the reported issue regarding the pie series throwing a null check exception with the pie series alone not rendering. Unfortunately, we wouldn't be able to reproduce the reported issue as we do not know the exact scenario in which the issue is occurring. We have tried the following scenarios in the test phase to reproduce the issues and also attached the sample below for reference.

- Ensured the rendering of the pie chart into a small container (size lesser than 300x300) along with data labels and legend enabled and tried closing and opening the application several times.

- Ensured the rendering of the pie chart along with data labels and legend enabled and tried changing the orientation of the device to portrait to landscape and vice versa.

So, we kindly request you modify the below-attached sample to replicate the reported issue and revert us along with the null check exception’s stack trace so that it will help us assist you in a better way.

Sample: [i402900.zip](https://github.com/syncfusion/flutter-examples/files/9470668/i402900.zip)


Regards,
Sriram Kiran

**Closed** 2022-12-28 08:13 UTC
