### ISSUE TITLE
issue about unable to load asset:

### ISSUE THREAD

**Issue by itsdani121** [syncfusion/flutter-examples#401] opened 2021-07-27 06:20 UTC
i am facing issue about this kindly guide me what can i do 

            [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: packages/timezone/data/2020a.tzf
E/flutter (14958): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
E/flutter (14958): <asynchronous suspension>
E/flutter (14958): #1      _SfCalendarState._loadDataBase (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart:2429:9)
E/flutter (14958): <asynchronous suspension>
E/flutter (14958):

pubspec.yaml file is :
                                  name: wsms_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.4+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  fluttertoast: ^8.0.7
  syncfusion_flutter_calendar: ^19.2.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#157087"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

         flutter doctor is 
            [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!

it did not load any text.

**Comment by Indumathi1195R** [comment] 2021-07-29 06:18
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Unable to load asset.**

We have already fixed the time zone package related issue in our weekly NuGet version 18.1.46-beta. Kindly update the latest version for resolving this issue.

Please find the changelog from the following link.

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_calendar/changelog#18146-beta---04282020

We hope that this helps you. If possible, can you please share the below details to us,

•	Issue reproducing scenario
•	Flutter version
•	Code snippet

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by itsdani121** [comment] 2021-07-29 06:27
hi i am not using beta verison instead of stable verison and flutter is
2.2.3 verison if i reduce flutter verison then it work fine. so kindly look
into this issue

**Comment by Indumathi1195R** [comment] 2021-07-30 06:02
Hi,

Thank you for the update.

We have ensured using the Flutter version 2.2.3 and Syncfusion Calendar version as 19.2.49 
and there is no issue related to time zone package. If possible, can you please check your project once and let us know if the time zone package was installed or not. We have attached the screenshot for the same.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/54974849/127607991-9b94ddee-7c7a-4a42-b346-3b9c033fece7.png)

Regards,
Indumathi R

**Comment by itsdani121** [comment] 2021-07-30 09:14
Yes it's already installed

**Comment by Indumathi1195R** [comment] 2021-08-02 10:42
Hi Team,

Thank you for the update.

We have ensured with the latest Flutter stable and beta versions, we are unable to reproduce the time zone-related issue from our end. We have prepared a simple sample for the same. Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with the following details.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_timezone-1225581337.zip

•	Code snippet of the calendar
•	Pubspec.yaml details
•	Calendar version
•	Flutter doctor details

It will be helpful for us to check on it and provide you solution at the earliest.

Regards,
Indumathi R

**Comment by waqas-younas-deriv** [comment] 2021-08-02 19:34
Hi, I have faced the same issue just run syncfusion_calendar on flutter 2.2.0, and you will get it.

**Unhandled Exception: Unable to load asset: packages/timezone/data/2020a.tzf**

**Closed** 2021-08-16 05:35 UTC
