### ISSUE TITLE
Flutter Pdfviewer Fatal error: Unexpectedly found nil while unwrapping an Optional value Swift:128

### ISSUE THREAD

**Issue by Taimoorsikander** [syncfusion/flutter-examples#768] opened 2023-04-19 23:20 UTC
Hi, I am using Flutter Pdfviewer, and it's working perfectly in any case but in iOS while the pdf is loading, I press the back button to close the screen or change it than the app crashes. This is the error that I'm getting
syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift:128: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by deepika134** [comment] 2023-05-05 03:55
We tried to reproduce the reported issue with provided details, but the PDF loads properly without any crashes in our side. For your reference, we have prepared a simple sample (along with the output scree record of the same) and it can be downloaded from the attachment.

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in the sample and share the issue replicating video, which will be helpful for us to provide a prompt solution at the earliest.
[github.zip](https://github.com/syncfusion/flutter-examples/files/11403160/github.zip)

**Comment by ramkumarsync** [comment] 2024-02-07 11:17
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the requested details to proceed further.

**Closed by ramkumarsync** 2024-02-07 11:17 UTC
