### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by salamay** [syncfusion/flutter-examples#636] opened 2022-06-07 13:30 UTC
Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.

**Comment by gilneyjr** [comment] 2022-06-08 16:44
I've got the same issue. Just upgrade Flutter to the newerst version and the issue should be fixed.

**Comment by salamay** [comment] 2022-06-08 17:09
Ok... Thanks

**Comment by Indumathi1195R** [comment] 2023-04-24 05:08
As per the shared information, we have checked the mentioned issue “**Error occurred while using the SchedulerBinding method in the Flutter Event  Calendar**” in the simple sample and we are unable to reproduce any error from our end. Also please find the tested details below.


Flutter Version: Channel stable – 3.0.0
Flutter Calendar version: 21.1.41

 

Can you please confirm are you using the latest Flutter version, if not kindly use the latest version and let us know still if you are facing same issue? It would be helpful for us to analyze and provide you a solution at the earliest.

**Comment by daradonn** [comment] 2023-04-29 02:31
Flutter: 2.8.1
syncfusion_flutter_calendar: 20.1.47
syncfusion_flutter_datepicker: 20.1.47
worked for me

**Comment by IndumathiR-1995** [comment] 2023-06-23 07:14
Hi daradonn,

Thanks for the update. Please get in touch with us if would you require further assistance.

Regards,
Indumathi R

**Closed** 2024-02-14 10:14 UTC
